const $ = s => document.querySelector(s);
const paths = {
 heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',
 home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',
 map:'m9 3-6 3v15l6-3 6 3 6-3V3l-6 3-6-3Zm0 0v15m6-12v15',
 book:'M4 3h7v18H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm9 0h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7M6 7h2m-2 4h2m9-4h2m-2 4h2',
 user:'M20 21v-2a7 7 0 0 0-14 0v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',
 arrow:'M5 12h14m-5-5 5 5-5 5',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',
 pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 calendar:'M4 5h16v16H4ZM8 2v6m8-6v6M4 11h16',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z',
 camera:'M3 7h4l2-3h6l2 3h4v14H3ZM16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',
 bluetooth:'m7 6 10 12-5 4V2l5 4L7 18',battery:'M2 7h17v10H2Zm20 3v4M5 10h10v4H5Z',
 mail:'M3 5h18v14H3ZM3 5l9 8 9-8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
 leaf:'M20 3C7 2 2 8 5 16s18 6 15-13ZM5 20 16 9',check:'m5 12 4 4L20 5',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Z',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7'
};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.heart}"/></svg>`}
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const heartObject=()=>`<div class="heart-object"><svg viewBox="0 0 120 110" aria-hidden="true"><defs><linearGradient id="heartGradient" x2=".9" y2="1"><stop stop-color="#f3d7ca"/><stop offset=".45" stop-color="#e5b6a5"/><stop offset="1" stop-color="#c58b79"/></linearGradient></defs><path d="M60 99C43 86 9 63 8 36 7 9 44 1 60 25 79 0 114 12 112 38 111 63 77 88 60 99Z" fill="url(#heartGradient)" stroke="#d9a995"/><path d="M20 32c3-14 20-16 28-7" fill="none" stroke="#fae6dc" stroke-width="4" stroke-linecap="round" opacity=".65"/><path d="M46 52h10l4-9 5 18 5-9h8" stroke="#fff1e4" fill="none" stroke-width="2" stroke-linecap="round"/><circle cx="61" cy="78" r="2" fill="#fff6d9"/></svg></div>`;
const seed=[
 {id:'cafe',title:'把下午，泡进一杯拿铁里',date:'2026-09-20',place:'梧桐街角咖啡馆',tag:'咖啡散步',note:'靠窗的位置，刚刚好的阳光。你负责喝咖啡，我负责陪着你。',image:'assets/doll-cafe.png'},
 {id:'home',title:'在家发呆，也是好日子',date:'2026-09-18',place:'我们的秘密基地',tag:'日常碎片',note:'没有特别的安排，抱着奶芙晒了一个下午的太阳。这样的普通日子，也想好好记住。',image:'assets/doll-hero.png'},
 {id:'walk',title:'一起收集，秋天的第一片叶子',date:'2026-09-15',place:'河畔小公园',tag:'一起出门',note:'沿着河边慢慢走，发现了一片心形的叶子。下次还想和你来这里。',image:''}
];
let state;
try{state=JSON.parse(XinZaiStorage.getItem('xinzai-v1'))}catch{}
if(!state||!Array.isArray(state.memories))state={name:'奶芙',memories:XinZaiNative.available?[]:seed,connected:!XinZaiNative.available,quiet:true,hidePlace:true,trip:null};
let page='home',memoryMode='all',query='',uploadedPhoto='',toastTimer,previousFocus;
function save(){try{XinZaiStorage.setItem('xinzai-v1',JSON.stringify(state));window.dispatchEvent(new Event('xinzai-state-saved'));return true}catch{toast('储存空间不足，请导出备份后减少照片');return false}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3300)}
function doll(){return escapeHTML(state.name)}
function dateLabel(date){return date.replaceAll('-','.');}
function routeMap(){return `<svg class="mini-map" viewBox="0 0 600 480" preserveAspectRatio="xMidYMid slice" aria-label="回忆地点示意地图"><rect width="600" height="480" fill="#edeee1"/><path d="M0 85Q150 140 220 28T450 80T660 60M-20 375Q90 305 200 390T420 345T650 370" stroke="#dce2c9" stroke-width="69" fill="none"/><path d="M390-50Q265 150 405 235T350 540" stroke="#d0dfe0" stroke-width="48" fill="none"/><g stroke="#fffdf3" stroke-width="14" fill="none"><path d="M0 215 600 170M0 310 600 280M120-20 160 500M-20 60 620 400M475-20 525 500"/></g><g stroke="#e4e1d2" stroke-width="1" fill="#e4e1d2"><rect x="205" y="120" width="53" height="34" rx="7"/><rect x="214" y="235" width="62" height="33" rx="7"/><rect x="43" y="240" width="46" height="38" rx="7"/><rect x="457" y="208" width="39" height="35" rx="7"/><rect x="230" y="320" width="38" height="54" rx="7"/></g><path d="M157 342Q205 233 288 206T458 132" fill="none" stroke="#9ca977" stroke-width="3" stroke-dasharray="5 7"/><g fill="#afb994"><circle cx="68" cy="116" r="11"/><circle cx="87" cy="102" r="9"/><circle cx="506" cy="356" r="13"/><circle cx="530" cy="340" r="9"/><circle cx="268" cy="72" r="11"/></g><g font-family="Microsoft YaHei,sans-serif" font-size="11" fill="#a2a58c"><text x="44" y="147">河畔公园</text><text x="425" y="390">慢慢走的小路</text><text x="196" y="186">梧桐街</text></g></svg>`}
function memoryCover(m){if(!XinZaiNative.available)return routeMap();return `<div class="memory-paper"><span>♡</span><small>把这一天，轻轻收好</small></div>`}
function memoryCard(m){return `<button class="memory-card ${m.image?'':'paper-card'}" data-action="memory" data-id="${escapeHTML(m.id)}"><div class="memory-image">${m.image?`<img src="${escapeHTML(m.image)}" alt="${escapeHTML(m.title)}" loading="lazy">`:memoryCover(m)}<span class="memory-date">${dateLabel(m.date)}</span></div><div class="memory-info"><h3>${escapeHTML(m.title)}</h3><p>${icon('pin')}${escapeHTML(m.place||'私藏的小瞬间')}<span class="heart">♡</span></p></div></button>`}
function heading(title,subtitle,action=''){return `<div class="page-heading"><div><div class="eyebrow">OUR LITTLE WORLD</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function home(){return `<div class="greeting"><div><div class="eyebrow">A LITTLE COMPANY, A LOT OF LOVE</div><h1>今天，也想和你在一起 <span class="sun">☼</span></h1><p>那些平凡的小日子，因为有你，都闪闪发光。</p></div><span class="date-tag">${icon('calendar')} 2026.09.22 · 秋日正好</span></div>
 <div class="home-grid"><div><section class="hero"><img src="assets/doll-hero.png" alt="戴兔耳帽的奶芙坐在奶油色毛毯上，胸前有一颗粉色心脏"><div class="hero-copy"><span class="pill"><span class="green-dot"></span>${state.connected?`${doll()}在你身边`:'今天，也可以手动记忆'}</span><h2>世界很大，<br>我们<em>一起</em>慢慢逛。</h2><p>口袋里装着小小的我，<br>心里装着和你一起的每一天。</p><button class="primary" data-action="trip">${icon(state.trip?'pin':'leaf')}${state.trip?'查看进行中的旅程':'带我出门吧'}${icon('arrow')}</button></div><span class="hero-sticker"><span>♡</span> 和你一起，就是好天气</span></section><div class="stats-bar"><div class="stat"><strong>${state.memories.length}</strong>篇<small>被珍藏的小回忆</small></div><div class="stat"><strong>${new Set(state.memories.map(m=>m.place).filter(Boolean)).size}</strong>处<small>一起留下的足迹</small></div><div class="stat"><strong>${state.memories.filter(m=>m.image).length}</strong>张<small>照片里的小幸福</small></div></div></div>
 <div><section class="device-card"><div class="card-heading"><span>我们之间的小小心跳</span><span class="tiny">DEMO</span></div>${heartObject()}<h3>${doll()}的心脏</h3><p>${state.connected?'轻轻靠近，就有了连接。':'还没连接，也可以留住今天。'}</p><div class="device-stats"><span>${icon('bluetooth')}${state.connected?'已连接':'未连接'} · 模拟</span><span>${icon('battery')}86% · 模拟</span></div><button class="outline-button" data-action="device">${icon('heart')}查看我的心跳</button></section><button class="whisper" data-action="inbox" style="width:100%;text-align:left">${icon('mail')}<div><p>“那天下午的阳光，我还记得。”</p><small>${doll()}有一句悄悄话想对你说 ${icon('arrow')}</small></div></button></div></div>
 <div class="section-title"><h2>我们的小回忆 <span>LITTLE MOMENTS</span></h2><button class="text-button" data-page="memories">翻开回忆簿 ${icon('arrow')}</button></div><div class="memory-grid home-memories">${state.memories.slice(0,3).map(memoryCard).join('')||empty()}</div>`}
function empty(){return `<div class="empty-state">${icon('book')}<p>第一份回忆，等你来写。</p><button class="primary" data-action="new">留下一个瞬间</button></div>`}
function memories(){let shown=state.memories.filter(m=>[m.title,m.place,m.note,m.tag,m.date].join(' ').toLowerCase().includes(query.toLowerCase()));if(memoryMode==='out')shown=shown.filter(m=>m.tag==='一起出门'||m.tag==='咖啡散步');return `${heading('把日子，装进回忆里','一张照片，一段小事。每一页都有我们。',`<button class="primary" data-action="new">${icon('plus')}留下一个瞬间</button>`)}<div class="toolbar"><div class="segmented" aria-label="回忆筛选">${[['all','全部回忆'],['out','一起出门'],['calendar','日历']].map(([key,name])=>`<button class="${memoryMode===key?'active':''}" data-action="filter" data-filter="${key}">${name}</button>`).join('')}</div><input class="search-field" type="search" id="memory-search" placeholder="搜索地点、日期或小故事…" aria-label="搜索回忆" value="${escapeHTML(query)}"></div><div id="memory-results">${memoryMode==='calendar'?calendar(shown):`<div class="memory-grid">${shown.map(memoryCard).join('')}</div>${shown.length?'':query?'<div class="empty-state">还没有找到这段回忆，换个词试试吧。</div>':empty()}`}</div><p class="view-note">${icon('shield')} 回忆仅保存在当前浏览器。可以在「我的」中导出备份。</p>`}
function calendar(items){const today=new Date();const month=items[0]?.date?.slice(0,7)||`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;const [y,m]=month.split('-').map(Number);const days=new Date(y,m,0).getDate();const offset=(new Date(y,m-1,1).getDay()+6)%7;return `<p style="margin:0 0 15px;font-size:13px">${y} 年 ${m} 月 <span class="tiny">· 按筛选结果中最新回忆所在月份展示</span></p><div class="calendar">${['一','二','三','四','五','六','日'].map(d=>`<div class="weekday">周${d}</div>`).join('')}${'<div></div>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const entries=items.filter(e=>e.date===`${month}-${String(i+1).padStart(2,'0')}`);return entries.length?`<button data-action="day" data-date="${month}-${String(i+1).padStart(2,'0')}">${i+1}${entries[0].image?`<img src="${escapeHTML(entries[0].image)}" alt="这一天的回忆">`:' ♡'}${entries.length>1?`<small>+${entries.length-1}</small>`:''}</button>`:`<div>${i+1}</div>`}).join('')}</div>`}
function journey(){const trips=state.memories.filter(m=>m.place);return `${heading('每一程，都有你','走过的路，会变成我们故事的一部分。',`<button class="primary" data-action="trip">${icon('leaf')}${state.trip?'旅程进行中':'一起出发'}</button>`)}${state.trip?`<div class="trip-panel"><div>正在演示记录一次出门<small>从 ${escapeHTML(state.trip.place)} 出发 · 不采集真实位置</small></div><button class="primary" data-action="finish-trip">结束并写回忆</button></div>`:''}<div class="map-layout"><div class="map-board">${routeMap()}<div class="map-note">${icon('map')} 我们的回忆地图 · 地点示意</div>${trips.slice(0,3).map((m,i)=>`<button class="map-pin" style="left:${[44,21,71][i]}%;top:${[38,63,21][i]}%" data-action="memory" data-id="${escapeHTML(m.id)}" aria-label="查看${escapeHTML(m.place)}的回忆">${m.image?`<img src="${escapeHTML(m.image)}" alt="">`:'<span>♡</span>'}</button>`).join('')}<div class="map-bottom"><span>♡ ${trips.length} 份有地点的回忆</span><span class="tiny">点击标记，重温那一天</span></div></div><div class="timeline"><h3>一起走过的地方 <span class="tiny">OUR FOOTPRINTS</span></h3>${trips.slice(0,5).map(m=>`<div class="timeline-item"><small>${dateLabel(m.date)} · ${escapeHTML(m.tag)}</small><h4>${escapeHTML(m.place)}</h4><p>${escapeHTML(m.title)}</p><button class="text-button" data-action="memory" data-id="${escapeHTML(m.id)}">翻开这段回忆 ${icon('arrow')}</button></div>`).join('')||'<p class="tiny">带我去一个新地方吧。</p>'}</div></div><p class="view-note">此地图是交互示意，标记不是实际坐标。正式版由手机定位记录地点，蓝牙心脏确认娃娃在身边。</p>`}
function profile(){return `${heading('小小的我，和大大的你','这里藏着，我们独一无二的联系。')}<div class="profile-grid"><section class="doll-passport"><div class="eyebrow">MY LITTLE SOULMATE</div><img class="passport-image" src="assets/doll-hero.png" alt="娃娃奶芙"><h2>${doll()}</h2><p>喜欢晒太阳，也喜欢陪着你。<br>是有一点慢热的小小冒险家。</p><div class="tags"><span>棉花娃娃</span><span>温柔慢热</span><span>奶油色的小宇宙</span></div><button class="outline-button" data-action="rename">编辑娃娃昵称 ${icon('arrow')}</button></section><div><section class="settings-card"><h3>我们之间的连接</h3><div class="setting-row"><span>${doll()}的心脏<small>模拟${state.connected?'已连接 · 电量 86%':'未连接'}，点击查看硬件概念</small></span><button class="text-button" data-action="device">查看 ${icon('arrow')}</button></div><div class="setting-row"><span>安静陪伴<small>产品偏好演示：不催促、不惩罚，不制造断签焦虑</small></span><button class="switch ${state.quiet?'on':''}" role="switch" aria-checked="${state.quiet}" aria-label="安静陪伴" data-action="toggle-quiet"></button></div></section><section class="settings-card"><h3>把回忆，安心收藏</h3><div class="setting-row"><span>分享时隐藏地点<small>制作回忆卡片时，默认不带地点文字</small></span><button class="switch ${state.hidePlace?'on':''}" role="switch" aria-checked="${state.hidePlace}" aria-label="分享时隐藏地点" data-action="toggle-place"></button></div><div class="setting-row"><span>带走我们的回忆<small>导出包含照片的 JSON 备份文件</small></span><button class="text-button" data-action="backup">导出 ${icon('download')}</button></div><div class="setting-row"><span>找回备份的回忆<small>导入心仔导出的 JSON 文件，替换当前回忆</small></span><button class="text-button" data-action="restore">导入 ${icon('arrow')}</button></div></section></div></div>`}
function render(focus=false){const labels={home:'今日陪伴',journey:'一起走过',memories:'我们的回忆',profile:'我的小世界'};$('#navigation').innerHTML=[['home','heart','陪伴'],['journey','map','足迹'],['memories','book','回忆'],['profile','user','我的']].map(([id,ic,title])=>`<button class="nav-item ${page===id?'active':''}" data-page="${id}" ${page===id?'aria-current="page"':''} aria-label="${title}">${icon(ic)}<span>${title}</span>${page===id?'<i class="nav-dot"></i>':''}</button>`).join('');$('#page-label').textContent=labels[page];$('#inbox-button').innerHTML=icon('mail');$('#view').innerHTML=({home,journey,memories,profile}[page]||home)();if(focus)$('#view').focus({preventScroll:true})}
function go(next){page=next;location.hash=next;render(true);window.scrollTo({top:0,behavior:'instant'})}
function modal(title,body){previousFocus=document.activeElement;$('#modal-content').innerHTML=`<div class="modal-header"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close" aria-label="关闭">${icon('close')}</button></div><div class="modal-body">${body}</div>`;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){$('#modal').close();if(previousFocus?.isConnected)previousFocus.focus()}
function showDevice(){modal('一颗心脏，一份陪伴',`<div class="device-large">${heartObject()}<h3>${doll()}的心脏</h3><p>圆润心形外壳 · 奶油蜜桃配色<br>设计概念，具体尺寸与工艺待工程验证。</p><div class="device-detail"><div><small>连接状态</small>${state.connected?'蓝牙已连接':'未连接'} · 模拟</div><div><small>剩余电量</small>86% · 演示数值</div><div><small>记录方式</small>蓝牙在场 + 手机定位</div><div><small>轻轻回应</small>柔光与短促震动 · 概念</div></div><button class="primary full-width" data-action="heartbeat">${icon('heart')}感受一下心跳动画</button><button class="text-button" style="margin-top:17px" data-action="toggle-device">${state.connected?'模拟断开连接':'模拟连接心脏'}</button><p class="view-note" style="margin-top:17px">原型只演示连接状态和动画，不会调用设备蓝牙、震动或定位。</p></div>`)}
function newMemory(existing=null,tripDraft=false){uploadedPhoto=existing?.image||'';const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;modal(existing?'再写一点，那天的故事':'留下一个小小的瞬间',`<p>不必写得很长，有你和${doll()}就好。</p><form id="memory-form" data-id="${escapeHTML(existing?.id||'')}" data-trip="${tripDraft}"><label class="upload-label"><span id="upload-preview">${uploadedPhoto?`<img src="${escapeHTML(uploadedPhoto)}" alt="选中的照片">`:icon('camera')+' 选一张我们的照片'}</span><input type="file" id="photo-input" accept="image/jpeg,image/png,image/webp" aria-label="选择照片"></label><label class="form-field">这份回忆的名字<input name="title" required maxlength="40" placeholder="例如：和你一起晒太阳" value="${escapeHTML(existing?.title||'')}"></label><div class="form-two"><label class="form-field">是哪一天<input type="date" name="date" required value="${existing?.date||today}"></label><label class="form-field">给它一个小标签<select name="tag">${['日常碎片','一起出门','咖啡散步','追星打卡'].map(t=>`<option ${(existing?.tag||(tripDraft?'一起出门':''))===t?'selected':''}>${t}</option>`).join('')}</select></label></div><label class="form-field">在哪里 <span class="tiny">· 可以留空</span><input name="place" maxlength="50" placeholder="只写自己喜欢的地点昵称就好" value="${escapeHTML(existing?.place||(tripDraft?state.trip?.place:'')||'')}"></label><label class="form-field">想记住的小事<textarea name="note" maxlength="600" placeholder="那天的阳光、路边的小花，还有你的心情…">${escapeHTML(existing?.note||'')}</textarea></label><button type="button" class="text-button" data-action="draft">${icon('spark')}用轻陪伴口吻写个草稿 <span class="tiny">· 本地模板</span></button><p class="view-note">照片只保存在当前浏览器，不会上传到服务器。</p><button class="primary full-width" style="margin-top:15px" type="submit">${icon('heart')}把这一刻收好</button></form>`)}
function openMemory(id){const m=state.memories.find(e=>e.id===id);if(!m)return;modal('这一页，是我们的',`<div class="card-preview">${m.image?`<img src="${escapeHTML(m.image)}" alt="${escapeHTML(m.title)}">`:`<div style="height:190px;overflow:hidden;border-radius:8px;margin-bottom:20px">${memoryCover(m)}</div>`}<small>${dateLabel(m.date)} · ${escapeHTML(m.tag)}</small><h3 style="margin-top:12px">${escapeHTML(m.title)}</h3><p>${escapeHTML(m.note)}</p><small>♡ ${doll()} & YOU · 心仔</small></div><label class="privacy-check"><input id="share-place" type="checkbox" ${state.hidePlace?'':'checked'}>在导出的卡片中加入地点（默认保护我们的私密足迹）</label><div class="modal-actions"><button class="outline-button" data-action="edit" data-id="${escapeHTML(id)}">编辑回忆</button><button class="primary" data-action="export-card" data-id="${escapeHTML(id)}">${icon('download')}保存回忆卡</button></div><button class="text-button danger" style="margin-top:20px" data-action="delete" data-id="${escapeHTML(id)}">${icon('trash')}删除这一份回忆</button>`)}
function startTrip(){if(state.trip){go('journey');return}modal('今天，想一起去哪里？',`<p>正式版会在你主动开始后，用手机定位记录旅程。这个原型用你填写的地点演示流程，不会获取真实位置。</p><form id="trip-form"><label class="form-field">今天的目的地<input name="place" required maxlength="50" placeholder="例如：梧桐街角的咖啡馆"></label><div class="letter" style="font-size:12px">“带上我吧。<br>无论去哪里，都想陪你一起。”</div><p class="view-note">${state.connected?'心脏已连接（模拟）':'心脏未连接（模拟），本次将以手动出门记录继续。'}</p><button class="primary full-width" type="submit" style="margin-top:18px">${icon('leaf')}出发，把今天变成回忆</button></form>`)}
async function downloadBlob(blob,name){if(XinZaiNative.available){await XinZaiNative.exportBlob(blob,name);return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function exportCard(id){const m=state.memories.find(e=>e.id===id);if(!m)return;const includePlace=$('#share-place')?.checked;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1440;const c=canvas.getContext('2d');c.fillStyle=m.template==='pink'?'#f4e1e0':m.template==='ticket'?'#edeedb':'#f5efdf';c.fillRect(0,0,1080,1440);c.fillStyle='#fffdf5';c.fillRect(45,45,990,1350);try{if(m.image){const img=new Image();img.src=m.image;await img.decode();const ratio=Math.max(910/img.width,790/img.height),w=img.width*ratio,h=img.height*ratio;c.save();c.beginPath();c.rect(85,85,910,790);c.clip();c.drawImage(img,85+(910-w)/2,85+(790-h)/2,w,h);c.restore()}else{c.fillStyle='#e9ecd9';c.fillRect(85,85,910,790);c.fillStyle='#a2ac87';c.font='150px Georgia';c.textAlign='center';c.fillText('♡',540,510)}}catch{toast('照片未能载入，请重新选择图片再试');return}c.textAlign='center';c.fillStyle='#9a8f7b';c.font='23px "Microsoft YaHei", sans-serif';c.fillText(`${dateLabel(m.date)} · ${m.tag}${m.mood?' · '+m.mood:''}`,540,931);c.fillStyle='#575346';c.font='36px "Microsoft YaHei", sans-serif';wrapText(c,m.title,540,997,880,49,2);c.fillStyle='#978b78';c.font='25px "Microsoft YaHei", sans-serif';wrapText(c,m.note||'和你在一起，普通的一天也值得珍藏。',540,1110,820,42,3);if(includePlace&&m.place){c.font='22px "Microsoft YaHei", sans-serif';c.fillText(m.place.slice(0,35),540,1290)}c.fillStyle='#aaa086';c.font='22px "Microsoft YaHei", sans-serif';c.fillText(`♡ ${state.name} & YOU · 心仔 XINZAI`,540,1350);canvas.toBlob(async blob=>{if(blob){try{await downloadBlob(blob,`心仔-${m.date}-回忆卡.png`);toast('回忆卡已保存')}catch(error){toast(error.message)}}else toast('导出失败，请稍后再试')},'image/png')}
function wrapText(c,text,x,y,width,lineHeight,maxLines){let line='',lines=[];for(const char of text){if(c.measureText(line+char).width>width||char==='\n'){lines.push(line);line=char==='\n'?'':char}else line+=char}if(line)lines.push(line);if(lines.length>maxLines){lines=lines.slice(0,maxLines);lines[maxLines-1]=lines[maxLines-1].slice(0,-1)+'…'}lines.forEach((l,i)=>c.fillText(l,x,y+i*lineHeight))}
async function loadPhoto(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('请选择 JPG、PNG 或 WebP 图片');return}if(file.size>15*1024*1024){toast('请选择 15 MB 以内的照片');return}const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const ratio=Math.min(1,1000/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=img.width*ratio;c.height=img.height*ratio;const ctx=c.getContext('2d');ctx.fillStyle='#fffdf7';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);uploadedPhoto=c.toDataURL('image/jpeg',.8);$('#upload-preview').innerHTML=`<img src="${uploadedPhoto}" alt="选中的回忆照片">`;toast('照片已选好，仅保存在当前浏览器')}catch{toast('这张照片未能打开，请换一张试试')}finally{URL.revokeObjectURL(url)}}
async function backup(){try{const data=JSON.parse(JSON.stringify(state));for(const m of data.memories){if(m.image?.startsWith('assets/')){const img=new Image();img.src=m.image;await img.decode();const ratio=Math.min(1,1000/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=img.width*ratio;canvas.height=img.height*ratio;canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);m.image=canvas.toDataURL('image/jpeg',.8)}}await downloadBlob(new Blob([JSON.stringify({format:'xinzai-backup-v1',data},null,2)],{type:'application/json'}),'心仔-回忆备份.json');toast('包含照片的回忆备份已导出')}catch(error){toast(XinZaiNative.available?error.message:'备份未完成，请通过本地预览地址打开后重试')}}
function restore(){modal('让回忆回到这里',`<p>选择心仔导出的 JSON 备份。确认导入后会替换当前浏览器中的回忆，建议先导出当前备份。</p><form id="restore-form"><label class="form-field">选择备份文件<input type="file" id="restore-file" accept="application/json,.json" required></label><label class="privacy-check"><input type="checkbox" required>我已备份需要保留的内容，同意用备份替换当前回忆。</label><button class="primary full-width" type="submit" style="margin-top:20px">确认导入备份</button></form>`)}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-page],[data-action]');if(!target)return;if(target.dataset.page){go(target.dataset.page);return}const action=target.dataset.action,id=target.dataset.id;switch(action){case'close':closeModal();break;case'profile':go('profile');break;case'new':newMemory();break;case'memory':openMemory(id);break;case'edit':newMemory(state.memories.find(m=>m.id===id));break;case'device':showDevice();break;case'heartbeat':$('.device-large .heart-object')?.classList.remove('beating');requestAnimationFrame(()=>$('.device-large .heart-object')?.classList.add('beating'));toast('扑通，扑通。我在这里。 · 动画演示');break;case'toggle-device':state.connected=!state.connected;save();render();showDevice();break;case'trip':startTrip();break;case'finish-trip':newMemory(null,true);break;case'filter':memoryMode=target.dataset.filter;render();break;case'day':query=target.dataset.date;memoryMode='all';render();break;case'toggle-quiet':state.quiet=!state.quiet;save();render();toast('陪伴偏好已保存 · 当前原型不发送通知');break;case'toggle-place':state.hidePlace=!state.hidePlace;save();render();break;case'export-card':await exportCard(id);break;case'backup':await backup();break;case'restore':restore();break;case'inbox':modal(`${doll()}的一封小来信`,`<p>轻陪伴文案示例 · 由本地模板展示</p><div class="letter">那天下午的阳光，我还记得。<br>还有你把我放在窗边，说这里的光很好看。<br><br>原来被你带在身边，<br>就是我最喜欢的小事。<small>一直陪着你的 ${doll()} ♡</small></div><button class="primary full-width" data-action="close">把这份温柔收好</button>`);break;case'rename':modal('给小小的我，一个名字',`<form id="name-form"><label class="form-field">娃娃昵称<input name="name" maxlength="10" required value="${doll()}"></label><button class="primary full-width" type="submit">就叫这个名字</button></form>`);break;case'draft':{const form=$('#memory-form');const place=form.elements.place.value.trim();const old=form.elements.note.value.trim();if(old){toast('先保留你写下的话，清空内容后可以生成新草稿');break}form.elements.note.value=`${place?`今天和你一起去了${place}。`:'今天，又和你一起度过了一个小小的日常。'}没有什么大事发生，但被你带在身边，就是值得收藏的瞬间。`;if(!form.elements.title.value.trim())form.elements.title.value='和你一起，普通的一天也闪闪发光';break}case'delete':modal('要和这一页说再见吗？',`<p>仅删除这份回忆及其中的照片。删除后不能撤销，已经导出的卡片不受影响。</p><div class="modal-actions"><button class="outline-button" data-action="memory" data-id="${escapeHTML(id)}">再留一会儿</button><button class="primary" data-action="confirm-delete" data-id="${escapeHTML(id)}">确认删除</button></div>`);break;case'confirm-delete':{const old=state.memories;state.memories=state.memories.filter(m=>m.id!==id);if(!save()){state.memories=old;break}closeModal();render();toast('这份回忆已删除');break}}});
document.addEventListener('input',e=>{if(e.target.id==='memory-search'){query=e.target.value;const tmp=document.createElement('div');tmp.innerHTML=memories();$('#memory-results').innerHTML=tmp.querySelector('#memory-results').innerHTML}});
document.addEventListener('change',e=>{if(e.target.id==='photo-input')loadPhoto(e.target.files[0])});
document.addEventListener('submit',async e=>{if(!['memory-form','trip-form','name-form','restore-form'].includes(e.target.id))return;e.preventDefault();const form=e.target,values=new FormData(form);if(form.id==='memory-form'){if(!values.get('title').trim()){toast('给这段回忆起个小名字吧');return}const old=JSON.parse(JSON.stringify(state));const m={id:form.dataset.id||`m-${Date.now()}`,title:values.get('title').trim(),date:values.get('date'),place:values.get('place').trim(),tag:values.get('tag'),note:values.get('note').trim(),image:uploadedPhoto,city:String(values.get('city')||'').trim().slice(0,20),mood:String(values.get('mood')||'平静'),template:String(values.get('template')||'cream'),track:form.dataset.trip==='true'?(window.xinzaiPendingTrack||null):(state.memories.find(x=>x.id===form.dataset.id)?.track||null)};state.memories=state.memories.filter(x=>x.id!==m.id);state.memories.push(m);state.memories.sort((a,b)=>b.date.localeCompare(a.date));if(form.dataset.trip==='true')state.trip=null;if(!save()){state=old;return}closeModal();query='';memoryMode='all';go('memories');toast('收好啦，又多了一段我们的故事 ♡')}else if(form.id==='trip-form'){const place=values.get('place').trim();if(!place){toast('写下今天想去的地方吧');return}state.trip={place,started:Date.now()};save();closeModal();go('journey');toast('演示旅程已开始，不采集真实位置')}else if(form.id==='name-form'){const name=values.get('name').trim();if(!name){toast('名字不能只有空格哦');return}state.name=name;save();closeModal();render();toast('新名字已收好 ♡')}else if(form.id==='restore-form'){const file=$('#restore-file').files[0];try{if(!file||file.size>25*1024*1024)throw Error('size');const imported=JSON.parse(await file.text());if(imported.format!=='xinzai-backup-v1'||!Array.isArray(imported.data?.memories)||typeof imported.data.name!=='string'||!imported.data.name.trim())throw Error('format');const incoming=imported.data;if(incoming.memories.length>500)throw Error('size');const ids=new Set();for(const m of incoming.memories){if(!['id','title','date','place','tag','note','image'].every(k=>typeof m[k]==='string'))throw Error('format');if(ids.has(m.id)||m.id.length>100||m.title.length>40||m.place.length>50||m.note.length>600||!/^\d{4}-\d{2}-\d{2}$/.test(m.date))throw Error('format');ids.add(m.id);if(m.image&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(m.image))throw Error('image')}if(window.xinzaiValidateBackup)window.xinzaiValidateBackup(incoming);const old=state;state={name:incoming.name.slice(0,10),memories:incoming.memories,connected:XinZaiNative.available?false:!!incoming.connected,quiet:!!incoming.quiet,hidePlace:incoming.hidePlace!==false,trip:null,onboarded:true,birthday:String(incoming.birthday||'').slice(0,10),personality:String(incoming.personality||'温柔慢热').slice(0,20)};if(!save()){state=old;return}closeModal();render();toast('回忆已经回来啦')}catch{toast('无法导入，请选择有效的心仔备份（25 MB 以内）')}}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
window.addEventListener('hashchange',()=>{const hash=location.hash.slice(1);if(['home','journey','memories','profile'].includes(hash)&&hash!==page){page=hash;render(true)}});
page=['home','journey','memories','profile'].includes(location.hash.slice(1))?location.hash.slice(1):'home';render();
